---
- name: Setup docusaurus
  hosts: docusaurus
  vars:
    nginx_vhosts:
    - listen: "80"
      server_name: "docusaurus.gdg-demo.com"
      root: "/var/www/docusaurus"
      index: "index.html"

  roles:
  - { role: nginx, tags: nginx }
  - { role: deploy, tags: update }